// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpirionUITests.Tests
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("PlayBooksLogic")]
    public partial class PlayBooksLogicFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "PlayBooksLogic.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Tests", "PlayBooksLogic", "\tTests containing all scanning on Local", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
#line 5
 testRunner.Given("User is logged in", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 6
 testRunner.Then("Create directory on Local machine", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Given User is trying to test playbook logics for AccessDate AND DataTypes")]
        [NUnit.Framework.TestCaseAttribute("AccessDate_On_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;On", "Social Security Number", "SDM SD Local AccessDate On_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_On", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Before_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Before", "Social Security Number", "SDM SD Local AccessDate Before_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Before", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_After_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;After", "Social Security Number", "SDM SD Local AccessDate After_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_After", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_NotOn_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Not On", "Social Security Number", "SDM SD Local AccessDate NotOn_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_NotOn", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Today_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Today", "Social Security Number", "SDM SD Local AccessDate Today_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Today", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Yesterday_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Yesterday", "Social Security Number", "SDM SD Local AccessDate Yesterday_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Yesterday", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_OnOrBefore_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;On Or Before", "Social Security Number", "SDM SD Local AccessDate OnOrBefore_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_OnOrBefore", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_OnOrAfter_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;On Or After", "Social Security Number", "SDM SD Local AccessDate OnOrAfter_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_OnOrAfter", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last7Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last 7 Days", "Social Security Number", "SDM SD Local AccessDate Last7Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last7Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last30Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last 30 Days", "Social Security Number", "SDM SD Local AccessDate Last30Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last30Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last365D_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last 365 Days", "Social Security Number", "SDM SD Local AccessDate Last365D_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last365Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_LastWeek_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last Week", "Social Security Number", "SDM SD Local AccessDate LastWeek_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_LastWeek", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_LastMonth_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last Month", "Social Security Number", "SDM SD Local AccessDate LastMonth_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_LastMonth", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_ThisWeek_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;This Week", "Social Security Number", "SDM SD Local AccessDate ThisWk_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_ThisWeek", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_ThisMonth_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;This Month", "Social Security Number", "SDM SD Local AccessDate ThisMth_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_ThisMonth", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_LastYear_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last Year", "Social Security Number", "SDM SD Local AccessDate LastYear_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_LastYear", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_ThisYear_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;This Year", "Social Security Number", "SDM SD Local AccessDate ThisYear_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_ThisYear", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last4Months_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last X Months", "Social Security Number", "SDM SD Local AccessDate Last4Mts_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last4Months", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last4Weeks_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last X Weeks", "Social Security Number", "SDM SD Local AccessDate Last4Wks_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last4Weeks", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last4Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last X Days", "Social Security Number", "SDM SD Local AccessDate Last4Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last4Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last4Years_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last X Years", "Social Security Number", "SDM SD Local AccessDate Last4Years_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last4Years", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_Last4Hours_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;Last X Hours", "Social Security Number", "SDM SD Local AccessDate Last4Hours_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_Last4Hours", "TestData\\TestData.csv", null)]
        public virtual void GivenUserIsTryingToTestPlaybookLogicsForAccessDateANDDataTypes(
                    string playBookName, 
                    string playBookDescription, 
                    string leftDecision, 
                    string rightDecision, 
                    string logicName, 
                    string logicType, 
                    string logicTypeOption, 
                    string scanItem, 
                    string scanName, 
                    string scanDescription, 
                    string scanType, 
                    string scanTargetType, 
                    string scanLocationType, 
                    string folderPath, 
                    string testFile, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("PlayBookName", playBookName);
            argumentsOfScenario.Add("PlayBookDescription", playBookDescription);
            argumentsOfScenario.Add("LeftDecision", leftDecision);
            argumentsOfScenario.Add("RightDecision", rightDecision);
            argumentsOfScenario.Add("LogicName", logicName);
            argumentsOfScenario.Add("LogicType", logicType);
            argumentsOfScenario.Add("LogicTypeOption", logicTypeOption);
            argumentsOfScenario.Add("ScanItem", scanItem);
            argumentsOfScenario.Add("ScanName", scanName);
            argumentsOfScenario.Add("ScanDescription", scanDescription);
            argumentsOfScenario.Add("ScanType", scanType);
            argumentsOfScenario.Add("ScanTargetType", scanTargetType);
            argumentsOfScenario.Add("ScanLocationType", scanLocationType);
            argumentsOfScenario.Add("FolderPath", folderPath);
            argumentsOfScenario.Add("TestFile", testFile);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Given User is trying to test playbook logics for AccessDate AND DataTypes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 9
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' at \'{0}\' for \'SocialSecurityNumber\' from \'{1}" +
                            "\'  with \'{2}\' and uploading to \'{3}\', \'true\'", scanTargetType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 10
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'SocialSecurityNumber\' from \'{1}\'  with \'" +
                            "{2}\' and uploading to \'{3}\', \'false\'", scanTargetType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.Then("User is waiting for the dashboard to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 12
 testRunner.Then("User selects to click on new scan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 13
 testRunner.Then(string.Format("User finds the created playbook or create new one \'{0}\',\'{1}\',\'{2}\', \'{3}\',\'{4}\'," +
                            "\'{5}\' ,\'{6}\' and \'{7}\'", playBookName, playBookDescription, logicName, logicType, logicTypeOption, leftDecision, rightDecision, scanItem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 14
 testRunner.Then(string.Format("user is setting up the file access time \'{0}\'", logicTypeOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 15
 testRunner.Then(string.Format("User creates a new SSD scan with \'{0}\', \'ScanType\',\'{1}\', \'{2}\', \'{3}\',\'{4}\', \'{5" +
                            "}\', \'{6}\'", scanName, scanDescription, playBookName, scanType, scanTargetType, scanLocationType, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 16
 testRunner.Then("Run the scan and wait for scan to complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 17
 testRunner.And("Open Search Scan Results and verify playbook logic details are correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Given User is trying to test playbook logics for AccessDate Or DataTypes")]
        [NUnit.Framework.TestCaseAttribute("AccessDate_ValidAD_On__Or_InvalidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;On", "Social Security Number", "SDM SD Local ValidAD_Or_InvalidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_On", "TestData\\TestData.csv", "true", "InvalidSSN", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_InValidAD_On__Or_ValidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;On", "Social Security Number", "SDM SD Local InValidAD_On__Or_ValidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_On", "TestData\\TestData.csv", "false", "SocialSecurityNumber", null)]
        [NUnit.Framework.TestCaseAttribute("AccessDate_InValidAD_On__Or_InvalidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Access Date", "Contains;On", "Social Security Number", "SDM SD Local InValidAD_Or_InvalidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\AccessDate\\AccessDate_On", "TestData\\TestData.csv", "false", "InvalidSSN", null)]
        public virtual void GivenUserIsTryingToTestPlaybookLogicsForAccessDateOrDataTypes(
                    string playBookName, 
                    string playBookDescription, 
                    string leftDecision, 
                    string rightDecision, 
                    string logicName, 
                    string logicType, 
                    string logicTypeOption, 
                    string scanItem, 
                    string scanName, 
                    string scOrescription, 
                    string scanType, 
                    string scanTargetType, 
                    string scanLocationType, 
                    string folderPath, 
                    string testFile, 
                    string scenario, 
                    string sSNType, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("PlayBookName", playBookName);
            argumentsOfScenario.Add("PlayBookDescription", playBookDescription);
            argumentsOfScenario.Add("LeftDecision", leftDecision);
            argumentsOfScenario.Add("RightDecision", rightDecision);
            argumentsOfScenario.Add("LogicName", logicName);
            argumentsOfScenario.Add("LogicType", logicType);
            argumentsOfScenario.Add("LogicTypeOption", logicTypeOption);
            argumentsOfScenario.Add("ScanItem", scanItem);
            argumentsOfScenario.Add("ScanName", scanName);
            argumentsOfScenario.Add("ScOrescription", scOrescription);
            argumentsOfScenario.Add("ScanType", scanType);
            argumentsOfScenario.Add("ScanTargetType", scanTargetType);
            argumentsOfScenario.Add("ScanLocationType", scanLocationType);
            argumentsOfScenario.Add("FolderPath", folderPath);
            argumentsOfScenario.Add("TestFile", testFile);
            argumentsOfScenario.Add("Scenario", scenario);
            argumentsOfScenario.Add("SSNType", sSNType);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Given User is trying to test playbook logics for AccessDate Or DataTypes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 49
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'{1}\' from \'{2}\'  with \'{3}\' and uploadin" +
                            "g to \'{4}\', \'true\'", scanTargetType, sSNType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 50
 testRunner.Then("User is waiting for the dashboard to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 51
 testRunner.Then("User selects to click on new scan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 52
 testRunner.Then(string.Format("User finds the created playbook or create new one \'{0}\',\'{1}\',\'{2}\', \'{3}\',\'{4}\'," +
                            "\'{5}\' ,\'{6}\' and \'{7}\'", playBookName, playBookDescription, logicName, logicType, logicTypeOption, leftDecision, rightDecision, scanItem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 53
 testRunner.Then(string.Format("user is setting up file access time \'{0}\' \'{1}\'", logicTypeOption, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 54
 testRunner.Then(string.Format("User creates a new SSD scan with \'{0}\', \'ScanType\',\'{1}\', \'{2}\', \'{3}\',\'{4}\', \'{5" +
                            "}\', \'{6}\'", scanName, scOrescription, playBookName, scanType, scanTargetType, scanLocationType, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 55
 testRunner.Then("Run the scan and wait for scan to complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 56
 testRunner.And(string.Format("Open Search Scan Results and verify playbook OR logic details are correct \'{0}\' \'" +
                            "{1}\'", sSNType, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Given User is trying to test playbook logics for CreateDate Or DataTypes")]
        [NUnit.Framework.TestCaseAttribute("CreateDate_ValidAD_On__Or_InvalidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;On", "Social Security Number", "SDM SD Local ValidAD_Or_InvalidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_On", "TestData\\TestData.csv", "true", "InvalidSSN", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_InValidAD_On__Or_ValidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;On", "Social Security Number", "SDM SD Local InValidAD_On__Or_ValidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_On", "TestData\\TestData.csv", "false", "SocialSecurityNumber", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_InValidAD_On__Or_InvalidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;On", "Social Security Number", "SDM SD Local InValidAD_Or_InvalidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_On", "TestData\\TestData.csv", "false", "InvalidSSN", null)]
        public virtual void GivenUserIsTryingToTestPlaybookLogicsForCreateDateOrDataTypes(
                    string playBookName, 
                    string playBookDescription, 
                    string leftDecision, 
                    string rightDecision, 
                    string logicName, 
                    string logicType, 
                    string logicTypeOption, 
                    string scanItem, 
                    string scanName, 
                    string scOrescription, 
                    string scanType, 
                    string scanTargetType, 
                    string scanLocationType, 
                    string folderPath, 
                    string testFile, 
                    string scenario, 
                    string sSNType, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("PlayBookName", playBookName);
            argumentsOfScenario.Add("PlayBookDescription", playBookDescription);
            argumentsOfScenario.Add("LeftDecision", leftDecision);
            argumentsOfScenario.Add("RightDecision", rightDecision);
            argumentsOfScenario.Add("LogicName", logicName);
            argumentsOfScenario.Add("LogicType", logicType);
            argumentsOfScenario.Add("LogicTypeOption", logicTypeOption);
            argumentsOfScenario.Add("ScanItem", scanItem);
            argumentsOfScenario.Add("ScanName", scanName);
            argumentsOfScenario.Add("ScOrescription", scOrescription);
            argumentsOfScenario.Add("ScanType", scanType);
            argumentsOfScenario.Add("ScanTargetType", scanTargetType);
            argumentsOfScenario.Add("ScanLocationType", scanLocationType);
            argumentsOfScenario.Add("FolderPath", folderPath);
            argumentsOfScenario.Add("TestFile", testFile);
            argumentsOfScenario.Add("Scenario", scenario);
            argumentsOfScenario.Add("SSNType", sSNType);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Given User is trying to test playbook logics for CreateDate Or DataTypes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 65
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'{1}\' from \'{2}\'  with \'{3}\' and uploadin" +
                            "g to \'{4}\', \'true\'", scanTargetType, sSNType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 66
 testRunner.Then("User is waiting for the dashboard to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 67
 testRunner.Then("User selects to click on new scan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 68
 testRunner.Then(string.Format("User finds the created playbook or create new one \'{0}\',\'{1}\',\'{2}\', \'{3}\',\'{4}\'," +
                            "\'{5}\' ,\'{6}\' and \'{7}\'", playBookName, playBookDescription, logicName, logicType, logicTypeOption, leftDecision, rightDecision, scanItem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 69
 testRunner.Then(string.Format("user is setting up file create time \'{0}\' \'{1}\'", logicTypeOption, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 70
 testRunner.Then(string.Format("User creates a new SSD scan with \'{0}\', \'ScanType\',\'{1}\', \'{2}\', \'{3}\',\'{4}\', \'{5" +
                            "}\', \'{6}\'", scanName, scOrescription, playBookName, scanType, scanTargetType, scanLocationType, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 71
 testRunner.Then("Run the scan and wait for scan to complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 72
 testRunner.And(string.Format("Open Search Scan Results and verify playbook OR logic details are correct \'{0}\' \'" +
                            "{1}\'", sSNType, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Given User is trying to test playbook logics for ModifyDate Or DataTypes")]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_ValidAD_On__Or_InvalidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;On", "Social Security Number", "SDM SD Local ValidAD_Or_InvalidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_On", "TestData\\TestData.csv", "true", "InvalidSSN", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_InValidAD_On__Or_ValidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;On", "Social Security Number", "SDM SD Local InValidAD_On__Or_ValidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_On", "TestData\\TestData.csv", "false", "SocialSecurityNumber", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_InValidAD_On__Or_InvalidSSN_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;On", "Social Security Number", "SDM SD Local InValidAD_Or_InvalidSSN_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_On", "TestData\\TestData.csv", "false", "InvalidSSN", null)]
        public virtual void GivenUserIsTryingToTestPlaybookLogicsForModifyDateOrDataTypes(
                    string playBookName, 
                    string playBookDescription, 
                    string leftDecision, 
                    string rightDecision, 
                    string logicName, 
                    string logicType, 
                    string logicTypeOption, 
                    string scanItem, 
                    string scanName, 
                    string scOrescription, 
                    string scanType, 
                    string scanTargetType, 
                    string scanLocationType, 
                    string folderPath, 
                    string testFile, 
                    string scenario, 
                    string sSNType, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("PlayBookName", playBookName);
            argumentsOfScenario.Add("PlayBookDescription", playBookDescription);
            argumentsOfScenario.Add("LeftDecision", leftDecision);
            argumentsOfScenario.Add("RightDecision", rightDecision);
            argumentsOfScenario.Add("LogicName", logicName);
            argumentsOfScenario.Add("LogicType", logicType);
            argumentsOfScenario.Add("LogicTypeOption", logicTypeOption);
            argumentsOfScenario.Add("ScanItem", scanItem);
            argumentsOfScenario.Add("ScanName", scanName);
            argumentsOfScenario.Add("ScOrescription", scOrescription);
            argumentsOfScenario.Add("ScanType", scanType);
            argumentsOfScenario.Add("ScanTargetType", scanTargetType);
            argumentsOfScenario.Add("ScanLocationType", scanLocationType);
            argumentsOfScenario.Add("FolderPath", folderPath);
            argumentsOfScenario.Add("TestFile", testFile);
            argumentsOfScenario.Add("Scenario", scenario);
            argumentsOfScenario.Add("SSNType", sSNType);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Given User is trying to test playbook logics for ModifyDate Or DataTypes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 80
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 81
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'{1}\' from \'{2}\'  with \'{3}\' and uploadin" +
                            "g to \'{4}\', \'true\'", scanTargetType, sSNType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 82
 testRunner.Then("User is waiting for the dashboard to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 83
 testRunner.Then("User selects to click on new scan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 84
 testRunner.Then(string.Format("User finds the created playbook or create new one \'{0}\',\'{1}\',\'{2}\', \'{3}\',\'{4}\'," +
                            "\'{5}\' ,\'{6}\' and \'{7}\'", playBookName, playBookDescription, logicName, logicType, logicTypeOption, leftDecision, rightDecision, scanItem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 85
 testRunner.Then(string.Format("user is setting up file modify time \'{0}\' \'{1}\'", logicTypeOption, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 86
 testRunner.Then(string.Format("User creates a new SSD scan with \'{0}\', \'ScanType\',\'{1}\', \'{2}\', \'{3}\',\'{4}\', \'{5" +
                            "}\', \'{6}\'", scanName, scOrescription, playBookName, scanType, scanTargetType, scanLocationType, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 87
 testRunner.Then("Run the scan and wait for scan to complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 88
 testRunner.And(string.Format("Open Search Scan Results and verify playbook OR logic details are correct \'{0}\' \'" +
                            "{1}\'", sSNType, scenario), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Given User is trying to test playbook logics for CreateDate AND DataTypes")]
        [NUnit.Framework.TestCaseAttribute("CreateDate_On_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;On", "Social Security Number", "SDM SD Local CreateDate On_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_On", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Before_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Before", "Social Security Number", "SDM SD Local CreateDate Before_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Before", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_After_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;After", "Social Security Number", "SDM SD Local CreateDate After_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_After", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_NotOn_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Not On", "Social Security Number", "SDM SD Local CreateDate NotOn_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_NotOn", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Today_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Today", "Social Security Number", "SDM SD Local CreateDate Today_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Today", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Yesterday_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Yesterday", "Social Security Number", "SDM SD Local CreateDate Yesterday_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Yesterday", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_OnOrBefore_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;On Or Before", "Social Security Number", "SDM SD Local CreateDate OnOrBefore_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_OnOrBefore", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_OnOrAfter_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;On Or After", "Social Security Number", "SDM SD Local CreateDate OnOrAfter_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_OnOrAfter", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last7Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last 7 Days", "Social Security Number", "SDM SD Local CreateDate Last7Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last7Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last30Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last 30 Days", "Social Security Number", "SDM SD Local CreateDate Last30Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last30Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last365D_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last 365 Days", "Social Security Number", "SDM SD Local CreateDate Last365D_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last365Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_LastWeek_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last Week", "Social Security Number", "SDM SD Local CreateDate LastWeek_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_LastWeek", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_LastMonth_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last Month", "Social Security Number", "SDM SD Local CreateDate LastMonth_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_LastMonth", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_ThisWeek_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;This Week", "Social Security Number", "SDM SD Local CreateDate ThisWk_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_ThisWeek", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_ThisMonth_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;This Month", "Social Security Number", "SDM SD Local CreateDate ThisMth_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_ThisMonth", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_LastYear_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last Year", "Social Security Number", "SDM SD Local CreateDate LastYear_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_LastYear", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_ThisYear_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;This Year", "Social Security Number", "SDM SD Local CreateDate ThisYear_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_ThisYear", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last4Months_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last X Months", "Social Security Number", "SDM SD Local CreateDate Last4Mts_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last4Months", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last4Weeks_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last X Weeks", "Social Security Number", "SDM SD Local CreateDate Last4Wks_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last4Weeks", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last4Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last X Days", "Social Security Number", "SDM SD Local CreateDate Last4Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last4Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last4Years_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last X Years", "Social Security Number", "SDM SD Local CreateDate Last4Years_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last4Years", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("CreateDate_Last4Hours_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Create Date", "Contains;Last X Hours", "Social Security Number", "SDM SD Local CreateDate Last4Hours_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\CreateDate\\CreateDate_Last4Hours", "TestData\\TestData.csv", null)]
        public virtual void GivenUserIsTryingToTestPlaybookLogicsForCreateDateANDDataTypes(
                    string playBookName, 
                    string playBookDescription, 
                    string leftDecision, 
                    string rightDecision, 
                    string logicName, 
                    string logicType, 
                    string logicTypeOption, 
                    string scanItem, 
                    string scanName, 
                    string scanDescription, 
                    string scanType, 
                    string scanTargetType, 
                    string scanLocationType, 
                    string folderPath, 
                    string testFile, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("PlayBookName", playBookName);
            argumentsOfScenario.Add("PlayBookDescription", playBookDescription);
            argumentsOfScenario.Add("LeftDecision", leftDecision);
            argumentsOfScenario.Add("RightDecision", rightDecision);
            argumentsOfScenario.Add("LogicName", logicName);
            argumentsOfScenario.Add("LogicType", logicType);
            argumentsOfScenario.Add("LogicTypeOption", logicTypeOption);
            argumentsOfScenario.Add("ScanItem", scanItem);
            argumentsOfScenario.Add("ScanName", scanName);
            argumentsOfScenario.Add("ScanDescription", scanDescription);
            argumentsOfScenario.Add("ScanType", scanType);
            argumentsOfScenario.Add("ScanTargetType", scanTargetType);
            argumentsOfScenario.Add("ScanLocationType", scanLocationType);
            argumentsOfScenario.Add("FolderPath", folderPath);
            argumentsOfScenario.Add("TestFile", testFile);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Given User is trying to test playbook logics for CreateDate AND DataTypes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 96
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 97
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'SocialSecurityNumber\' from \'{1}\'  with \'" +
                            "{2}\' and uploading to \'{3}\', \'true\'", scanTargetType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 98
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'SocialSecurityNumber\' from \'{1}\'  with \'" +
                            "{2}\' and uploading to \'{3}\', \'false\'", scanTargetType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 99
 testRunner.Then("User is waiting for the dashboard to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 100
 testRunner.Then("User selects to click on new scan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 101
 testRunner.Then(string.Format("User finds the created playbook or create new one \'{0}\',\'{1}\',\'{2}\', \'{3}\',\'{4}\'," +
                            "\'{5}\' ,\'{6}\' and \'{7}\'", playBookName, playBookDescription, logicName, logicType, logicTypeOption, leftDecision, rightDecision, scanItem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 102
 testRunner.Then(string.Format("user is setting up the file create time \'{0}\'", logicTypeOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 103
 testRunner.Then(string.Format("User creates a new SSD scan with \'{0}\', \'ScanType\',\'{1}\', \'{2}\', \'{3}\',\'{4}\', \'{5" +
                            "}\', \'{6}\'", scanName, scanDescription, playBookName, scanType, scanTargetType, scanLocationType, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 104
 testRunner.Then("Run the scan and wait for scan to complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 105
 testRunner.And("Open Search Scan Results and verify playbook logic details are correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Given User is trying to test playbook logics for ModifyDate AND DataTypes")]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_On_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;On", "Social Security Number", "SDM SD Local ModifyDate On_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_On", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Before_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Before", "Social Security Number", "SDM SD Local ModifyDate Before_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Before", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_After_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;After", "Social Security Number", "SDM SD Local ModifyDate After_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_After", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_NotOn_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Not On", "Social Security Number", "SDM SD Local ModifyDate NotOn_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_NotOn", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Today_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Today", "Social Security Number", "SDM SD Local ModifyDate Today_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Today", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Yesterday_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Yesterday", "Social Security Number", "SDM SD Local ModifyDate Yesterday_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Yesterday", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_OnOrBefore_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;On Or Before", "Social Security Number", "SDM SD Local ModifyDate OnOrBefore_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_OnOrBefore", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_OnOrAfter_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;On Or After", "Social Security Number", "SDM SD Local ModifyDate OnOrAfter_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_OnOrAfter", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last7Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last 7 Days", "Social Security Number", "SDM SD Local ModifyDate Last7Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last7Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last30Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last 30 Days", "Social Security Number", "SDM SD Local ModifyDate Last30Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last30Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last365D_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last 365 Days", "Social Security Number", "SDM SD Local ModifyDate Last365D_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last365Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_LastWeek_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last Week", "Social Security Number", "SDM SD Local ModifyDate LastWeek_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_LastWeek", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_LastMonth_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last Month", "Social Security Number", "SDM SD Local ModifyDate LastMonth_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_LastMonth", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_ThisWeek_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;This Week", "Social Security Number", "SDM SD Local ModifyDate ThisWk_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_ThisWeek", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_ThisMonth_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;This Month", "Social Security Number", "SDM SD Local ModifyDate ThisMth_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_ThisMonth", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_LastYear_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last Year", "Social Security Number", "SDM SD Local ModifyDate LastYear_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_LastYear", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_ThisYear_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;This Year", "Social Security Number", "SDM SD Local ModifyDate ThisYear_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_ThisYear", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last4Months_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last X Months", "Social Security Number", "SDM SD Local ModifyDate Last4Mts_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last4Months", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last4Weeks_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last X Weeks", "Social Security Number", "SDM SD Local ModifyDate Last4Wks_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last4Weeks", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last4Days_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last X Days", "Social Security Number", "SDM SD Local ModifyDate Last4Days_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last4Days", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last4Years_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last X Years", "Social Security Number", "SDM SD Local ModifyDate Last4Years_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last4Years", "TestData\\TestData.csv", null)]
        [NUnit.Framework.TestCaseAttribute("ModifyDate_Last4Hours_And_APUID", "Do not delete or update this PlayBook", "Take No Action", "Classification", "Automation Logic", "Data Types;Modify Date", "Contains;Last X Hours", "Social Security Number", "SDM SD Local ModifyDate Last4Hours_And_AUID:", "This scan is developed by automation", "Files & Folders", "Local Target", "Custom Folder List", "\\SensitiveDataScan\\PlaybookLogic\\ModifyDate\\ModifyDate_Last4Hours", "TestData\\TestData.csv", null)]
        public virtual void GivenUserIsTryingToTestPlaybookLogicsForModifyDateANDDataTypes(
                    string playBookName, 
                    string playBookDescription, 
                    string leftDecision, 
                    string rightDecision, 
                    string logicName, 
                    string logicType, 
                    string logicTypeOption, 
                    string scanItem, 
                    string scanName, 
                    string scanDescription, 
                    string scanType, 
                    string scanTargetType, 
                    string scanLocationType, 
                    string folderPath, 
                    string testFile, 
                    string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("PlayBookName", playBookName);
            argumentsOfScenario.Add("PlayBookDescription", playBookDescription);
            argumentsOfScenario.Add("LeftDecision", leftDecision);
            argumentsOfScenario.Add("RightDecision", rightDecision);
            argumentsOfScenario.Add("LogicName", logicName);
            argumentsOfScenario.Add("LogicType", logicType);
            argumentsOfScenario.Add("LogicTypeOption", logicTypeOption);
            argumentsOfScenario.Add("ScanItem", scanItem);
            argumentsOfScenario.Add("ScanName", scanName);
            argumentsOfScenario.Add("ScanDescription", scanDescription);
            argumentsOfScenario.Add("ScanType", scanType);
            argumentsOfScenario.Add("ScanTargetType", scanTargetType);
            argumentsOfScenario.Add("ScanLocationType", scanLocationType);
            argumentsOfScenario.Add("FolderPath", folderPath);
            argumentsOfScenario.Add("TestFile", testFile);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Given User is trying to test playbook logics for ModifyDate AND DataTypes", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 136
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
#line 137
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'SocialSecurityNumber\' from \'{1}\'  with \'" +
                            "{2}\' and uploading to \'{3}\', \'true\'", scanTargetType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 138
 testRunner.Given(string.Format("User is preparing testData at \'{0}\' for \'SocialSecurityNumber\' from \'{1}\'  with \'" +
                            "{2}\' and uploading to \'{3}\', \'false\'", scanTargetType, testFile, logicTypeOption, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 139
 testRunner.Then("User is waiting for the dashboard to load", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 140
 testRunner.Then("User selects to click on new scan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 141
 testRunner.Then(string.Format("User finds the created playbook or create new one \'{0}\',\'{1}\',\'{2}\', \'{3}\',\'{4}\'," +
                            "\'{5}\' ,\'{6}\' and \'{7}\'", playBookName, playBookDescription, logicName, logicType, logicTypeOption, leftDecision, rightDecision, scanItem), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 142
 testRunner.Then(string.Format("user is setting up the file modify time \'{0}\'", logicTypeOption), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 143
 testRunner.Then(string.Format("User creates a new SSD scan with \'{0}\', \'ScanType\',\'{1}\', \'{2}\', \'{3}\',\'{4}\', \'{5" +
                            "}\', \'{6}\'", scanName, scanDescription, playBookName, scanType, scanTargetType, scanLocationType, folderPath), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 144
 testRunner.Then("Run the scan and wait for scan to complete", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 145
 testRunner.And("Open Search Scan Results and verify playbook logic details are correct", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
