Feature: PlayBooksLogic
	Tests containing all scanning on Local

Background:
	Given User is logged in
	Then Create directory on Local machine

Scenario Outline: Given User is trying to test playbook logics for AccessDate AND DataTypes
	Given User is preparing testData at '<ScanTargetType>' at '<ScanTargetType>' for 'SocialSecurityNumber' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'true'
	Given User is preparing testData at '<ScanTargetType>' for 'SocialSecurityNumber' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'false'
	Then User is waiting for the dashboard to load
	Then User selects to click on new scan
	Then User finds the created playbook or create new one '<PlayBookName>','<PlayBookDescription>','<LogicName>', '<LogicType>','<LogicTypeOption>','<LeftDecision>' ,'<RightDecision>' and '<ScanItem>'
	Then user is setting up the file access time '<LogicTypeOption>'
	Then User creates a new SSD scan with '<ScanName>', 'ScanType','<ScanDescription>', '<PlayBookName>', '<ScanType>','<ScanTargetType>', '<ScanLocationType>', '<FolderPath>'
	Then Run the scan and wait for scan to complete
	And Open Search Scan Results and verify playbook logic details are correct

	Examples:
		| PlayBookName                     | PlayBookDescription                   | LeftDecision   | RightDecision  | LogicName        | LogicType              | LogicTypeOption        | ScanItem               | ScanName                                     | ScanDescription                      | ScanType        | ScanTargetType | ScanLocationType   | FolderPath                                                         | TestFile              |
		| AccessDate_On_And_APUID          | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;On            | Social Security Number | SDM SD Local AccessDate On_And_AUID:         | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_On          | TestData\TestData.csv |
		| AccessDate_Before_And_APUID      | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Before        | Social Security Number | SDM SD Local AccessDate Before_And_AUID:     | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Before      | TestData\TestData.csv |
		| AccessDate_After_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;After         | Social Security Number | SDM SD Local AccessDate After_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_After       | TestData\TestData.csv |
		| AccessDate_NotOn_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Not On        | Social Security Number | SDM SD Local AccessDate NotOn_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_NotOn       | TestData\TestData.csv |
		| AccessDate_Today_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Today         | Social Security Number | SDM SD Local AccessDate Today_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Today       | TestData\TestData.csv |
		| AccessDate_Yesterday_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Yesterday     | Social Security Number | SDM SD Local AccessDate Yesterday_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Yesterday   | TestData\TestData.csv |
		| AccessDate_OnOrBefore_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;On Or Before  | Social Security Number | SDM SD Local AccessDate OnOrBefore_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_OnOrBefore  | TestData\TestData.csv |
		| AccessDate_OnOrAfter_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;On Or After   | Social Security Number | SDM SD Local AccessDate OnOrAfter_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_OnOrAfter   | TestData\TestData.csv |
		| AccessDate_Last7Days_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last 7 Days   | Social Security Number | SDM SD Local AccessDate Last7Days_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last7Days   | TestData\TestData.csv |
		| AccessDate_Last30Days_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last 30 Days  | Social Security Number | SDM SD Local AccessDate Last30Days_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last30Days  | TestData\TestData.csv |
		| AccessDate_Last365D_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last 365 Days | Social Security Number | SDM SD Local AccessDate Last365D_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last365Days | TestData\TestData.csv |
		| AccessDate_LastWeek_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last Week     | Social Security Number | SDM SD Local AccessDate LastWeek_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_LastWeek    | TestData\TestData.csv |
		| AccessDate_LastMonth_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last Month    | Social Security Number | SDM SD Local AccessDate LastMonth_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_LastMonth   | TestData\TestData.csv |
		| AccessDate_ThisWeek_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;This Week     | Social Security Number | SDM SD Local AccessDate ThisWk_And_AUID:     | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_ThisWeek    | TestData\TestData.csv |
		| AccessDate_ThisMonth_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;This Month    | Social Security Number | SDM SD Local AccessDate ThisMth_And_AUID:    | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_ThisMonth   | TestData\TestData.csv |
		| AccessDate_LastYear_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last Year     | Social Security Number | SDM SD Local AccessDate LastYear_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_LastYear    | TestData\TestData.csv |
		| AccessDate_ThisYear_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;This Year     | Social Security Number | SDM SD Local AccessDate ThisYear_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_ThisYear    | TestData\TestData.csv |
		| AccessDate_Last4Months_And_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last X Months | Social Security Number | SDM SD Local AccessDate Last4Mts_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last4Months | TestData\TestData.csv |
		| AccessDate_Last4Weeks_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last X Weeks  | Social Security Number | SDM SD Local AccessDate Last4Wks_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last4Weeks  | TestData\TestData.csv |
		| AccessDate_Last4Days_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last X Days   | Social Security Number | SDM SD Local AccessDate Last4Days_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last4Days   | TestData\TestData.csv |
		| AccessDate_Last4Years_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last X Years  | Social Security Number | SDM SD Local AccessDate Last4Years_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last4Years  | TestData\TestData.csv |
		| AccessDate_Last4Hours_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Last X Hours  | Social Security Number | SDM SD Local AccessDate Last4Hours_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_Last4Hours  | TestData\TestData.csv |

# Failing due to 2 playbooks showing the default discovery playbook
# Ignored due to a bug| AccessDate_OlderThanXMon_And_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Older Than X Months | Social Security Number | SDM SD Local AccessDate OlderXMths_And_AUID: | This scan is developed by automation | Files & Folders | Local Target | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_OlderThanXMonths | TestData\TestData.csv |
# Ignored due to a bug| AccessDate_OlderThanXD_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Older Than X Days   | Social Security Number | SDM SD Local AccessDate OlrThnXDs_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_OlderThanXDays   | TestData\TestData.csv |
# Ignored due to a bug| AccessDate_OlderThanXW_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;Older Than X Weeks  | Social Security Number | SDM SD Local AccessDate OlrThnXWks_And_AUID: | This scan is developed by automation | Files & Folders | Local Target | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_OlderThanXWeeks  | TestData\TestData.csv |
Scenario Outline: Given User is trying to test playbook logics for AccessDate Or DataTypes
	Given User is preparing testData at '<ScanTargetType>' for '<SSNType>' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'true'
	Then User is waiting for the dashboard to load
	Then User selects to click on new scan
	Then User finds the created playbook or create new one '<PlayBookName>','<PlayBookDescription>','<LogicName>', '<LogicType>','<LogicTypeOption>','<LeftDecision>' ,'<RightDecision>' and '<ScanItem>'
	Then user is setting up file access time '<LogicTypeOption>' '<Scenario>'
	Then User creates a new SSD scan with '<ScanName>', 'ScanType','<ScOrescription>', '<PlayBookName>', '<ScanType>','<ScanTargetType>', '<ScanLocationType>', '<FolderPath>'
	Then Run the scan and wait for scan to complete
	And Open Search Scan Results and verify playbook OR logic details are correct '<SSNType>' '<Scenario>'

	Examples:
		| PlayBookName                                 | PlayBookDescription                   | LeftDecision   | RightDecision  | LogicName        | LogicType              | LogicTypeOption | ScanItem               | ScanName                                       | ScOrescription                       | ScanType        | ScanTargetType | ScanLocationType   | FolderPath                                                | TestFile              | Scenario | SSNType              |
		| AccessDate_ValidAD_On__Or_InvalidSSN_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;On     | Social Security Number | SDM SD Local ValidAD_Or_InvalidSSN_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_On | TestData\TestData.csv | true     | InvalidSSN           |
		| AccessDate_InValidAD_On__Or_ValidSSN_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;On     | Social Security Number | SDM SD Local InValidAD_On__Or_ValidSSN_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_On | TestData\TestData.csv | false    | SocialSecurityNumber |
		| AccessDate_InValidAD_On__Or_InvalidSSN_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Access Date | Contains;On     | Social Security Number | SDM SD Local InValidAD_Or_InvalidSSN_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\AccessDate\AccessDate_On | TestData\TestData.csv | false    | InvalidSSN           |

Scenario Outline: Given User is trying to test playbook logics for CreateDate Or DataTypes
	Given User is preparing testData at '<ScanTargetType>' for '<SSNType>' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'true'
	Then User is waiting for the dashboard to load
	Then User selects to click on new scan
	Then User finds the created playbook or create new one '<PlayBookName>','<PlayBookDescription>','<LogicName>', '<LogicType>','<LogicTypeOption>','<LeftDecision>' ,'<RightDecision>' and '<ScanItem>'
	Then user is setting up file create time '<LogicTypeOption>' '<Scenario>'
	Then User creates a new SSD scan with '<ScanName>', 'ScanType','<ScOrescription>', '<PlayBookName>', '<ScanType>','<ScanTargetType>', '<ScanLocationType>', '<FolderPath>'
	Then Run the scan and wait for scan to complete
	And Open Search Scan Results and verify playbook OR logic details are correct '<SSNType>' '<Scenario>'

	Examples:
		| PlayBookName                                 | PlayBookDescription                   | LeftDecision   | RightDecision  | LogicName        | LogicType              | LogicTypeOption | ScanItem               | ScanName                                       | ScOrescription                       | ScanType        | ScanTargetType | ScanLocationType   | FolderPath                                                | TestFile              | Scenario | SSNType              |
		| CreateDate_ValidAD_On__Or_InvalidSSN_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;On     | Social Security Number | SDM SD Local ValidAD_Or_InvalidSSN_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_On | TestData\TestData.csv | true     | InvalidSSN           |
		| CreateDate_InValidAD_On__Or_ValidSSN_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;On     | Social Security Number | SDM SD Local InValidAD_On__Or_ValidSSN_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_On | TestData\TestData.csv | false    | SocialSecurityNumber |
		| CreateDate_InValidAD_On__Or_InvalidSSN_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;On     | Social Security Number | SDM SD Local InValidAD_Or_InvalidSSN_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_On | TestData\TestData.csv | false    | InvalidSSN           |

Scenario Outline: Given User is trying to test playbook logics for ModifyDate Or DataTypes
	Given User is preparing testData at '<ScanTargetType>' for '<SSNType>' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'true'
	Then User is waiting for the dashboard to load
	Then User selects to click on new scan
	Then User finds the created playbook or create new one '<PlayBookName>','<PlayBookDescription>','<LogicName>', '<LogicType>','<LogicTypeOption>','<LeftDecision>' ,'<RightDecision>' and '<ScanItem>'
	Then user is setting up file modify time '<LogicTypeOption>' '<Scenario>'
	Then User creates a new SSD scan with '<ScanName>', 'ScanType','<ScOrescription>', '<PlayBookName>', '<ScanType>','<ScanTargetType>', '<ScanLocationType>', '<FolderPath>'
	Then Run the scan and wait for scan to complete
	And Open Search Scan Results and verify playbook OR logic details are correct '<SSNType>' '<Scenario>'

	Examples:
		| PlayBookName                                 | PlayBookDescription                   | LeftDecision   | RightDecision  | LogicName        | LogicType              | LogicTypeOption | ScanItem               | ScanName                                       | ScOrescription                       | ScanType        | ScanTargetType | ScanLocationType   | FolderPath                                                | TestFile              | Scenario | SSNType              |
		| ModifyDate_ValidAD_On__Or_InvalidSSN_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;On     | Social Security Number | SDM SD Local ValidAD_Or_InvalidSSN_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_On | TestData\TestData.csv | true     | InvalidSSN           |
		| ModifyDate_InValidAD_On__Or_ValidSSN_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;On     | Social Security Number | SDM SD Local InValidAD_On__Or_ValidSSN_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_On | TestData\TestData.csv | false    | SocialSecurityNumber |
		| ModifyDate_InValidAD_On__Or_InvalidSSN_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;On     | Social Security Number | SDM SD Local InValidAD_Or_InvalidSSN_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_On | TestData\TestData.csv | false    | InvalidSSN           |

Scenario Outline: Given User is trying to test playbook logics for CreateDate AND DataTypes
	Given User is preparing testData at '<ScanTargetType>' for 'SocialSecurityNumber' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'true'
	Given User is preparing testData at '<ScanTargetType>' for 'SocialSecurityNumber' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'false'
	Then User is waiting for the dashboard to load
	Then User selects to click on new scan
	Then User finds the created playbook or create new one '<PlayBookName>','<PlayBookDescription>','<LogicName>', '<LogicType>','<LogicTypeOption>','<LeftDecision>' ,'<RightDecision>' and '<ScanItem>'
	Then user is setting up the file create time '<LogicTypeOption>'
	Then User creates a new SSD scan with '<ScanName>', 'ScanType','<ScanDescription>', '<PlayBookName>', '<ScanType>','<ScanTargetType>', '<ScanLocationType>', '<FolderPath>'
	Then Run the scan and wait for scan to complete
	And Open Search Scan Results and verify playbook logic details are correct

	Examples:
		| PlayBookName                     | PlayBookDescription                   | LeftDecision   | RightDecision  | LogicName        | LogicType              | LogicTypeOption        | ScanItem               | ScanName                                     | ScanDescription                      | ScanType        | ScanTargetType | ScanLocationType   | FolderPath                                                         | TestFile              |
		| CreateDate_On_And_APUID          | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;On            | Social Security Number | SDM SD Local CreateDate On_And_AUID:         | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_On          | TestData\TestData.csv |
		| CreateDate_Before_And_APUID      | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Before        | Social Security Number | SDM SD Local CreateDate Before_And_AUID:     | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Before      | TestData\TestData.csv |
		| CreateDate_After_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;After         | Social Security Number | SDM SD Local CreateDate After_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_After       | TestData\TestData.csv |
		| CreateDate_NotOn_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Not On        | Social Security Number | SDM SD Local CreateDate NotOn_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_NotOn       | TestData\TestData.csv |
		| CreateDate_Today_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Today         | Social Security Number | SDM SD Local CreateDate Today_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Today       | TestData\TestData.csv |
		| CreateDate_Yesterday_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Yesterday     | Social Security Number | SDM SD Local CreateDate Yesterday_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Yesterday   | TestData\TestData.csv |
		| CreateDate_OnOrBefore_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;On Or Before  | Social Security Number | SDM SD Local CreateDate OnOrBefore_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_OnOrBefore  | TestData\TestData.csv |
		| CreateDate_OnOrAfter_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;On Or After   | Social Security Number | SDM SD Local CreateDate OnOrAfter_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_OnOrAfter   | TestData\TestData.csv |
		| CreateDate_Last7Days_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last 7 Days   | Social Security Number | SDM SD Local CreateDate Last7Days_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last7Days   | TestData\TestData.csv |
		| CreateDate_Last30Days_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last 30 Days  | Social Security Number | SDM SD Local CreateDate Last30Days_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last30Days  | TestData\TestData.csv |
		| CreateDate_Last365D_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last 365 Days | Social Security Number | SDM SD Local CreateDate Last365D_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last365Days | TestData\TestData.csv |
		| CreateDate_LastWeek_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last Week     | Social Security Number | SDM SD Local CreateDate LastWeek_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_LastWeek    | TestData\TestData.csv |
		| CreateDate_LastMonth_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last Month    | Social Security Number | SDM SD Local CreateDate LastMonth_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_LastMonth   | TestData\TestData.csv |
		| CreateDate_ThisWeek_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;This Week     | Social Security Number | SDM SD Local CreateDate ThisWk_And_AUID:     | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_ThisWeek    | TestData\TestData.csv |
		| CreateDate_ThisMonth_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;This Month    | Social Security Number | SDM SD Local CreateDate ThisMth_And_AUID:    | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_ThisMonth   | TestData\TestData.csv |
		| CreateDate_LastYear_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last Year     | Social Security Number | SDM SD Local CreateDate LastYear_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_LastYear    | TestData\TestData.csv |
		| CreateDate_ThisYear_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;This Year     | Social Security Number | SDM SD Local CreateDate ThisYear_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_ThisYear    | TestData\TestData.csv |
		| CreateDate_Last4Months_And_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last X Months | Social Security Number | SDM SD Local CreateDate Last4Mts_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last4Months | TestData\TestData.csv |
		| CreateDate_Last4Weeks_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last X Weeks  | Social Security Number | SDM SD Local CreateDate Last4Wks_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last4Weeks  | TestData\TestData.csv |
		| CreateDate_Last4Days_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last X Days   | Social Security Number | SDM SD Local CreateDate Last4Days_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last4Days   | TestData\TestData.csv |
		| CreateDate_Last4Years_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last X Years  | Social Security Number | SDM SD Local CreateDate Last4Years_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last4Years  | TestData\TestData.csv |
		| CreateDate_Last4Hours_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Last X Hours  | Social Security Number | SDM SD Local CreateDate Last4Hours_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_Last4Hours  | TestData\TestData.csv |

#ignored beacause of bugs showing 2 playbooks and discovery being the default one
#	| CreateDate_OlderThanXMon_And_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Older Than X Months | Social Security Number | SDM SD Local CreateDate OlderXMths_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_OlderThanXMonths | TestData\TestData.csv |
#	| CreateDate_OlderThanXD_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Older Than X Days   | Social Security Number | SDM SD Local CreateDate OlrThnXDs_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_OlderThanXDays   | TestData\TestData.csv |
#	| CreateDate_OlderThanXW_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Create Date | Contains;Older Than X Weeks  | Social Security Number | SDM SD Local CreateDate OlrThnXWks_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\CreateDate\CreateDate_OlderThanXWeeks  | TestData\TestData.csv |
Scenario Outline: Given User is trying to test playbook logics for ModifyDate AND DataTypes
	Given User is preparing testData at '<ScanTargetType>' for 'SocialSecurityNumber' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'true'
	Given User is preparing testData at '<ScanTargetType>' for 'SocialSecurityNumber' from '<TestFile>'  with '<LogicTypeOption>' and uploading to '<FolderPath>', 'false'
	Then User is waiting for the dashboard to load
	Then User selects to click on new scan
	Then User finds the created playbook or create new one '<PlayBookName>','<PlayBookDescription>','<LogicName>', '<LogicType>','<LogicTypeOption>','<LeftDecision>' ,'<RightDecision>' and '<ScanItem>'
	Then user is setting up the file modify time '<LogicTypeOption>'
	Then User creates a new SSD scan with '<ScanName>', 'ScanType','<ScanDescription>', '<PlayBookName>', '<ScanType>','<ScanTargetType>', '<ScanLocationType>', '<FolderPath>'
	Then Run the scan and wait for scan to complete
	And Open Search Scan Results and verify playbook logic details are correct

	Examples:
		| PlayBookName                     | PlayBookDescription                   | LeftDecision   | RightDecision  | LogicName        | LogicType              | LogicTypeOption        | ScanItem               | ScanName                                     | ScanDescription                      | ScanType        | ScanTargetType | ScanLocationType   | FolderPath                                                         | TestFile              |
		| ModifyDate_On_And_APUID          | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;On            | Social Security Number | SDM SD Local ModifyDate On_And_AUID:         | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_On          | TestData\TestData.csv |
		| ModifyDate_Before_And_APUID      | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Before        | Social Security Number | SDM SD Local ModifyDate Before_And_AUID:     | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Before      | TestData\TestData.csv |
		| ModifyDate_After_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;After         | Social Security Number | SDM SD Local ModifyDate After_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_After       | TestData\TestData.csv |
		| ModifyDate_NotOn_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Not On        | Social Security Number | SDM SD Local ModifyDate NotOn_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_NotOn       | TestData\TestData.csv |
		| ModifyDate_Today_And_APUID       | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Today         | Social Security Number | SDM SD Local ModifyDate Today_And_AUID:      | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Today       | TestData\TestData.csv |
		| ModifyDate_Yesterday_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Yesterday     | Social Security Number | SDM SD Local ModifyDate Yesterday_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Yesterday   | TestData\TestData.csv |
		| ModifyDate_OnOrBefore_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;On Or Before  | Social Security Number | SDM SD Local ModifyDate OnOrBefore_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_OnOrBefore  | TestData\TestData.csv |
		| ModifyDate_OnOrAfter_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;On Or After   | Social Security Number | SDM SD Local ModifyDate OnOrAfter_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_OnOrAfter   | TestData\TestData.csv |
		| ModifyDate_Last7Days_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last 7 Days   | Social Security Number | SDM SD Local ModifyDate Last7Days_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last7Days   | TestData\TestData.csv |
		| ModifyDate_Last30Days_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last 30 Days  | Social Security Number | SDM SD Local ModifyDate Last30Days_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last30Days  | TestData\TestData.csv |
		| ModifyDate_Last365D_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last 365 Days | Social Security Number | SDM SD Local ModifyDate Last365D_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last365Days | TestData\TestData.csv |
		| ModifyDate_LastWeek_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last Week     | Social Security Number | SDM SD Local ModifyDate LastWeek_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_LastWeek    | TestData\TestData.csv |
		| ModifyDate_LastMonth_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last Month    | Social Security Number | SDM SD Local ModifyDate LastMonth_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_LastMonth   | TestData\TestData.csv |
		| ModifyDate_ThisWeek_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;This Week     | Social Security Number | SDM SD Local ModifyDate ThisWk_And_AUID:     | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_ThisWeek    | TestData\TestData.csv |
		| ModifyDate_ThisMonth_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;This Month    | Social Security Number | SDM SD Local ModifyDate ThisMth_And_AUID:    | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_ThisMonth   | TestData\TestData.csv |
		| ModifyDate_LastYear_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last Year     | Social Security Number | SDM SD Local ModifyDate LastYear_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_LastYear    | TestData\TestData.csv |
		| ModifyDate_ThisYear_And_APUID    | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;This Year     | Social Security Number | SDM SD Local ModifyDate ThisYear_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_ThisYear    | TestData\TestData.csv |
		| ModifyDate_Last4Months_And_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last X Months | Social Security Number | SDM SD Local ModifyDate Last4Mts_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last4Months | TestData\TestData.csv |
		| ModifyDate_Last4Weeks_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last X Weeks  | Social Security Number | SDM SD Local ModifyDate Last4Wks_And_AUID:   | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last4Weeks  | TestData\TestData.csv |
		| ModifyDate_Last4Days_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last X Days   | Social Security Number | SDM SD Local ModifyDate Last4Days_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last4Days   | TestData\TestData.csv |
		| ModifyDate_Last4Years_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last X Years  | Social Security Number | SDM SD Local ModifyDate Last4Years_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last4Years  | TestData\TestData.csv |
		| ModifyDate_Last4Hours_And_APUID  | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Last X Hours  | Social Security Number | SDM SD Local ModifyDate Last4Hours_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_Last4Hours  | TestData\TestData.csv |
#ignored
#| ModifyDate_OlderThanXMon_And_APUID | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Older Than X Months | Social Security Number | SDM SD Local ModifyDate OlderXMths_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_OlderThanXMonths | TestData\TestData.csv |
#| ModifyDate_OlderThanXD_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Older Than X Days   | Social Security Number | SDM SD Local ModifyDate OlrThnXDs_And_AUID:  | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_OlderThanXDays   | TestData\TestData.csv |
#| ModifyDate_OlderThanXW_And_APUID   | Do not delete or update this PlayBook | Take No Action | Classification | Automation Logic | Data Types;Modify Date | Contains;Older Than X Weeks  | Social Security Number | SDM SD Local ModifyDate OlrThnXWks_And_AUID: | This scan is developed by automation | Files & Folders | Local Target   | Custom Folder List | \SensitiveDataScan\PlaybookLogic\ModifyDate\ModifyDate_OlderThanXWeeks  | TestData\TestData.csv |